#!/bin/csh

set run_time = 01:30:00
set project  = climate
set queue    = short
set ntasks   = 24
set nthrds   = 1

set email = `getent passwd $LOGNAME|cut -d':' -f 5|awk '{n=split($0,a," "); print a[1]"."a[n]"@pnnl.gov"}'`
set file_link_run_dir = `pwd`/physup_calls_av1c.txt

## ====================================================================
#   Set CASE related variables
## ====================================================================
setenv CASE      ne30_av1c04p2_const_int_03162016
setenv MACH      constance
setenv COMPILER  intel
setenv COMPSET   FC5AV1C-04P2
setenv RES       ne30_ne30
setenv MAKE_J    24
setenv mods      'none' #$locdir/mods_$CASE #'none' for no mods directory

## ====================================================================
#   Define directories
## ====================================================================
setenv PTMP      /pic/scratch/$LOGNAME/csmruns
setenv SRCROOT   ~/acme/srccodes/perturb/cime5/ACME
setenv CASEROOT  ~$LOGNAME/CSM/CMIP5/$CASE
setenv RUNDIR    {$PTMP}/$CASE/run
setenv BLDDIR    {$PTMP}/$CASE/bld
#setenv ALT_DATA


#Remove old log files
/bin/rm -rf $RUNDIR/*.log.*
/bin/rm -rf $BLDDIR/*.bldlog.*


## ====================================================================
#   create new case
## ====================================================================
rm -rf $CASEROOT
cd  $SRCROOT/cime/scripts
echo '==== GIT STATUS OF THE SRC ===='
git st
git rev-parse HEAD
echo '==== GIT STATUS ENDS ===='
./create_newcase -case $CASEROOT -mach $MACH -res $RES -compset $COMPSET -compiler $COMPILER -project $project|| echo 'create_newcase failed' && exit -1

## ====================================================================
#   Modify xml file through xmlchange commands
## ====================================================================

#batch options:
cd  $CASEROOT
if ( $?queue) then
    ./xmlchange -file env_batch.xml -id JOB_QUEUE           -val $queue     || exit -1
endif
if ( $?run_time ) then
    ./xmlchange -file env_batch.xml -id JOB_WALLCLOCK_TIME  -val $run_time  || exit -1
endif
if ( $?project ) then
    ./xmlchange -file env_batch.xml -id PROJECT_REQUIRED    -val TRUE       || exit -1
    ./xmlchange -file env_batch.xml -id PROJECT             -val $project   || exit -1
endif

#tasks and threads:
cd $CASEROOT
if ( $ntasks > 0 ) then
    ./xmlchange -file env_mach_pes.xml -id NTASKS_ATM  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_LND  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_ICE  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_OCN  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_CPL  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_GLC  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_ROF  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_WAV  -val $ntasks || exit -1
    ./xmlchange -file env_mach_pes.xml -id NTASKS_ESP  -val $ntasks || exit -1
endif

if ( $nthrds > 0 ) then
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_ATM  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_LND  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_ICE  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_OCN  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_CPL  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_GLC  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_ROF  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_WAV  -val $nthrds|| exit -1
    ./xmlchange -file env_mach_pes.xml -id NTHRDS_ESP  -val $nthrds|| exit -1
endif


#build-time options:
cd $CASEROOT
./xmlchange -file env_build.xml -id GMAKE_J -val $MAKE_J || exit -1
./xmlchange -file env_build.xml -id EXEROOT -val $BLDDIR || exit -1
./xmlchange -file env_build.xml -id DEBUG   -val 'TRUE'  || exit -1

#run-time options:
cd $CASEROOT
cd $CASEROOT

./xmlchange -file env_run.xml -id  RESUBMIT       -val '0'      || exit -1
./xmlchange -file env_run.xml -id  STOP_N         -val '1'      || exit -1
./xmlchange -file env_run.xml -id  STOP_OPTION    -val 'nsteps' || exit -1
./xmlchange -file env_run.xml -id  REST_N         -val '1'      || exit -1
./xmlchange -file env_run.xml -id  REST_OPTION    -val 'nmonths'|| exit -1
./xmlchange -file env_run.xml -id  RUNDIR         -val $RUNDIR  || exit -1

cat <<EOF >! user_nl_cam
&camexp
 nhtfrq                  = 1
 mfilt                   = 1
 ndens                   = 1
 avgflag_pertape         = 'I'
 pergro                  = .true.
/
EOF

#------------------------
## configure/Build/Submit
#------------------------
#config:
cd $CASEROOT
./case.setup || echo 'cesm_setup FAILED ' && exit -1

#add email address
sed -i 's/^#SBATCH.*--mail-user=.*/#SBATCH --mail-user='$email'/g' case.run

#build:
cd $CASEROOT
if ( $mods != 'none' ) then
    ln -sf ${mods}/* SourceMods/src.cam || echo 'Error while linking mods directory' && exit -1
endif

./case.build ||echo 'Model failed to build' && exit -1

#make changes to case.run script:
if ( $?file_link_run_dir ) then
    #For EOS and TITAN, we have to copy as compute nodes can't see home directory
    /bin/cp -fL $file_link_run_dir $RUNDIR/physup_calls.txt || echo 'Error while linking/copying file in run directory directory' && exit -1
endif


#***DO NOT*** submit-run:
##./case.submit||echo 'Model failed to submit run' && exit -1
